In [1]:
import numpy as np # for array related computations

Defining vectors

In [2]:
v = np.array([1,-1,2])
w = np.array([2,5,2])

Vector Addition

In [3]:
print(v+w)

[3 4 4]


In [4]:
print(v-w)

[-1 -6  0]


Scalar Multiplication

In [5]:
print(3*v)

[ 3 -3  6]


Length of a Vector

In [6]:
print(np.linalg.norm(v)) #linalg - linear algebra module, norm - length of the vector

2.449489742783178


Dot product

In [7]:
s = np.dot(v,w)
print(s)

1
